apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-1
  Namespace: demo-app-1-ns
  labels:
    app: demo-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-1
  template:
    metadata:
      labels:
        app: demo-app-1
    spec:
      containers:
      - name: demo-app-1
        image: broland96/demo-app-1
        ports:
        - containerPort: 8080