apiVersion: v1
kind: Service
metadata:
  name: demo-app-1
  Namespace: demo-app-1-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  selector:
    app: demo-app-1
  type: NodePort